language: python

python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - nightly

# command to install dependencies
before_install:
    - sudo apt-get update
    - sudo apt-get install liblapack-dev gfortran openmpi-bin libopenmpi-dev python-mpi4py python-numpy libhdf5-openmpi-dev

install: 
    - travis_wait 30 pip install -r requirements.txt
    - export CC=mpicc
    - git clone https://github.com/h5py/h5py.git 
    - cd h5py && python setup.py configure --mpi && python setup.py build && sudo python setup.py install --prefix=/usr/local && cd .. && sudo rm -rf h5py


# command to run tests
script:
    - make
    - py.test --doctest-modules --cov-report term-missing --cov=fds
