language: python

sudo: required
dist: trusty

python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - nightly

# command to install dependencies
before_install:
    - sudo apt-get update
    - sudo apt-get install liblapack-dev gfortran openmpi-bin libopenmpi-dev python-numpy libhdf5-openmpi-dev python-mpi4py

install: 
    - travis_wait 30 pip install -r requirements.txt
    - export CC=mpicc
    - git clone https://github.com/h5py/h5py.git 
    - cd h5py && python setup.py configure --mpi && python setup.py build && python setup.py install && cd .. && rm -rf h5py
    - python setup.py install


# command to run tests
script:
    - make
    - py.test --doctest-modules --cov-report term-missing --cov=fds
